### ISSUE TITLE
Add Sub Category to an existing Category

### ISSUE THREAD

**Issue by abhishekgarg5800** [doonstore/d2shop-admin#7]
Add Sub Category to an existing Category.
Eg. I added Milk (Category) -> FullCream ( Sub Category)

Now if i want to Create a sub category in an existing Category, that is not possible.
So under Category add “Add Sub Category”. Under that give an dropdown option for the cateogry and a text box to enter the sub category.

**Comment by AnmolSethi** [comment]
There are two ways to add Sub - Category to an existing Category. 

1. Category -> Manage Category -> Add Sub - Category (One at a time).
2. Category -> Manage Category -> Edit button under Actions Tab -> We can add as many categories as we want in a list manner (comma separated)
